2021-02-07 00:54:05,900 ERROR 19802 nodejs.ClusterClientNoResponseError: client no response in 977513ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 19802
hostname: 192.168.0.101

2021-02-07 08:37:56,573 ERROR 19802 nodejs.ClusterClientNoResponseError: client no response in 1951482ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 19802
hostname: 192.168.0.101

2021-02-07 09:15:15,639 ERROR 19802 nodejs.ClusterClientNoResponseError: client no response in 2239062ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 19802
hostname: 192.168.0.101

2021-02-07 11:02:27,611 ERROR 21641 [-/127.0.0.1/-/0ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at Handshake.Sequence._packetToError (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Protocol._enqueue (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/mysql/lib/Connection.js:116:18)
    at Pool.getConnection (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: YES)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 21641
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-02-07 13:02:52,239 ERROR 21689 nodejs.ClusterClientNoResponseError: client no response in 5429248ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 21689
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-02-07 13:20:07,527 ERROR 21689 nodejs.ClusterClientNoResponseError: client no response in 1010856ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 21689
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-02-07 13:32:22,857 ERROR 21689 nodejs.ClusterClientNoResponseError: client no response in 571230ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 21689
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-02-07 22:20:15,958 ERROR 21689 nodejs.ClusterClientNoResponseError: client no response in 13039832ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 21689
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-02-08 08:06:00,157 ERROR 21689 nodejs.ClusterClientNoResponseError: client no response in 28843241ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 21689
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-02-08 12:43:41,561 ERROR 21689 nodejs.ClusterClientNoResponseError: client no response in 1021685ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 21689
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-02-08 12:56:10,834 ERROR 21689 nodejs.ClusterClientNoResponseError: client no response in 648147ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 21689
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-02-08 13:13:39,745 ERROR 21689 nodejs.ClusterClientNoResponseError: client no response in 580699ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 21689
hostname: shenyuxiaoyaodeMacBook-Pro.local

2021-02-08 13:26:29,340 ERROR 21689 nodejs.ClusterClientNoResponseError: client no response in 689402ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/shenyuxiaoyao/Desktop/project/react-blog-midlle/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 21689
hostname: shenyuxiaoyaodeMacBook-Pro.local

